# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'all_compare_b2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_all_compare_b2(object):
    def setupUi(self, all_compare_b2):
        all_compare_b2.setObjectName("all_compare_b2")
        all_compare_b2.resize(500, 418)
        all_compare_b2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(all_compare_b2)
        self.horizontalLayout.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(all_compare_b2)
        self.frame.setStyleSheet("QPushButton{\n"
"    color: rgb(77, 77, 77);\n"
"    border: 0.5px solid rgb(191, 191, 191);\n"
"    border-radius: 4px;\n"
"    padding-top:7px;\n"
"    padding-bottom:7px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #303f9f;\n"
"    border: 0px;\n"
"    color: #ffffff;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.s1_btn = QtWidgets.QPushButton(self.frame)
        self.s1_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s1_btn.setObjectName("s1_btn")
        self.verticalLayout.addWidget(self.s1_btn)
        self.s2_btn = QtWidgets.QPushButton(self.frame)
        self.s2_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s2_btn.setObjectName("s2_btn")
        self.verticalLayout.addWidget(self.s2_btn)
        self.s3_btn = QtWidgets.QPushButton(self.frame)
        self.s3_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s3_btn.setObjectName("s3_btn")
        self.verticalLayout.addWidget(self.s3_btn)
        self.s4_btn = QtWidgets.QPushButton(self.frame)
        self.s4_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s4_btn.setObjectName("s4_btn")
        self.verticalLayout.addWidget(self.s4_btn)
        self.s5_btn = QtWidgets.QPushButton(self.frame)
        self.s5_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s5_btn.setObjectName("s5_btn")
        self.verticalLayout.addWidget(self.s5_btn)
        self.s6_btn = QtWidgets.QPushButton(self.frame)
        self.s6_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s6_btn.setObjectName("s6_btn")
        self.verticalLayout.addWidget(self.s6_btn)
        self.s7_btn = QtWidgets.QPushButton(self.frame)
        self.s7_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s7_btn.setObjectName("s7_btn")
        self.verticalLayout.addWidget(self.s7_btn)
        self.s8_btn = QtWidgets.QPushButton(self.frame)
        self.s8_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s8_btn.setObjectName("s8_btn")
        self.verticalLayout.addWidget(self.s8_btn)
        self.horizontalLayout.addWidget(self.frame)
        self.stackedWidget = QtWidgets.QStackedWidget(all_compare_b2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.stackedWidget.setStyleSheet("QPushButton{\n"
"    color: rgb(77, 77, 77);\n"
"    border: 0.5px solid rgb(191, 191, 191);\n"
"    border-radius: 4px;\n"
"    padding-top:7px;\n"
"    padding-bottom:7px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #303f9f;\n"
"    border: 0px;\n"
"    color: #ffffff;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome_page = QtWidgets.QWidget()
        self.welcome_page.setObjectName("welcome_page")
        self.label = QtWidgets.QLabel(self.welcome_page)
        self.label.setGeometry(QtCore.QRect(30, 160, 171, 50))
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setStyleSheet("color: rgb(77, 77, 77);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.welcome_page)
        self.s1page = QtWidgets.QWidget()
        self.s1page.setObjectName("s1page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.s1page)
        self.verticalLayout_2.setSpacing(40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.s1page)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.s1n1_cekbox = QtWidgets.QCheckBox(self.s1page)
        self.s1n1_cekbox.setObjectName("s1n1_cekbox")
        self.verticalLayout_2.addWidget(self.s1n1_cekbox)
        self.s1n2_cekbox = QtWidgets.QCheckBox(self.s1page)
        self.s1n2_cekbox.setObjectName("s1n2_cekbox")
        self.verticalLayout_2.addWidget(self.s1n2_cekbox)
        self.s1apply_btn = QtWidgets.QPushButton(self.s1page)
        self.s1apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s1apply_btn.setAutoDefault(False)
        self.s1apply_btn.setDefault(False)
        self.s1apply_btn.setObjectName("s1apply_btn")
        self.verticalLayout_2.addWidget(self.s1apply_btn)
        self.frame_2 = QtWidgets.QFrame(self.s1page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.s1page)
        self.s2page = QtWidgets.QWidget()
        self.s2page.setObjectName("s2page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.s2page)
        self.verticalLayout_3.setSpacing(40)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.s2page)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3.addWidget(self.frame_5)
        self.s2n1_cekbox = QtWidgets.QCheckBox(self.s2page)
        self.s2n1_cekbox.setObjectName("s2n1_cekbox")
        self.verticalLayout_3.addWidget(self.s2n1_cekbox)
        self.s2n2_cekbox = QtWidgets.QCheckBox(self.s2page)
        self.s2n2_cekbox.setObjectName("s2n2_cekbox")
        self.verticalLayout_3.addWidget(self.s2n2_cekbox)
        self.s2apply_btn = QtWidgets.QPushButton(self.s2page)
        self.s2apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s2apply_btn.setAutoDefault(False)
        self.s2apply_btn.setDefault(False)
        self.s2apply_btn.setObjectName("s2apply_btn")
        self.verticalLayout_3.addWidget(self.s2apply_btn)
        self.frame_4 = QtWidgets.QFrame(self.s2page)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.s2page)
        self.s3page = QtWidgets.QWidget()
        self.s3page.setObjectName("s3page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.s3page)
        self.verticalLayout_4.setSpacing(30)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.s3page)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4.addWidget(self.frame_6)
        self.s3n1_cekbox = QtWidgets.QCheckBox(self.s3page)
        self.s3n1_cekbox.setObjectName("s3n1_cekbox")
        self.verticalLayout_4.addWidget(self.s3n1_cekbox)
        self.s3n2_cekbox = QtWidgets.QCheckBox(self.s3page)
        self.s3n2_cekbox.setObjectName("s3n2_cekbox")
        self.verticalLayout_4.addWidget(self.s3n2_cekbox)
        self.s3n3_cekbox = QtWidgets.QCheckBox(self.s3page)
        self.s3n3_cekbox.setObjectName("s3n3_cekbox")
        self.verticalLayout_4.addWidget(self.s3n3_cekbox)
        self.s3n4_cekbox = QtWidgets.QCheckBox(self.s3page)
        self.s3n4_cekbox.setObjectName("s3n4_cekbox")
        self.verticalLayout_4.addWidget(self.s3n4_cekbox)
        self.s3apply_btn = QtWidgets.QPushButton(self.s3page)
        self.s3apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s3apply_btn.setAutoDefault(False)
        self.s3apply_btn.setDefault(False)
        self.s3apply_btn.setObjectName("s3apply_btn")
        self.verticalLayout_4.addWidget(self.s3apply_btn)
        self.frame_7 = QtWidgets.QFrame(self.s3page)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.s3page)
        self.s4page = QtWidgets.QWidget()
        self.s4page.setObjectName("s4page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.s4page)
        self.verticalLayout_5.setSpacing(30)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.s4page)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5.addWidget(self.frame_8)
        self.s4n1_cekbox = QtWidgets.QCheckBox(self.s4page)
        self.s4n1_cekbox.setObjectName("s4n1_cekbox")
        self.verticalLayout_5.addWidget(self.s4n1_cekbox)
        self.s4n2_cekbox = QtWidgets.QCheckBox(self.s4page)
        self.s4n2_cekbox.setObjectName("s4n2_cekbox")
        self.verticalLayout_5.addWidget(self.s4n2_cekbox)
        self.s4n3_cekbox = QtWidgets.QCheckBox(self.s4page)
        self.s4n3_cekbox.setObjectName("s4n3_cekbox")
        self.verticalLayout_5.addWidget(self.s4n3_cekbox)
        self.s4apply_btn = QtWidgets.QPushButton(self.s4page)
        self.s4apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s4apply_btn.setAutoDefault(False)
        self.s4apply_btn.setDefault(False)
        self.s4apply_btn.setObjectName("s4apply_btn")
        self.verticalLayout_5.addWidget(self.s4apply_btn)
        self.frame_9 = QtWidgets.QFrame(self.s4page)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.s4page)
        self.s5page = QtWidgets.QWidget()
        self.s5page.setObjectName("s5page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.s5page)
        self.verticalLayout_6.setSpacing(30)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.s5page)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_6.addWidget(self.frame_10)
        self.s5n1_cekbox = QtWidgets.QCheckBox(self.s5page)
        self.s5n1_cekbox.setObjectName("s5n1_cekbox")
        self.verticalLayout_6.addWidget(self.s5n1_cekbox)
        self.s5n2_cekbox = QtWidgets.QCheckBox(self.s5page)
        self.s5n2_cekbox.setObjectName("s5n2_cekbox")
        self.verticalLayout_6.addWidget(self.s5n2_cekbox)
        self.s5apply_btn = QtWidgets.QPushButton(self.s5page)
        self.s5apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s5apply_btn.setAutoDefault(False)
        self.s5apply_btn.setDefault(False)
        self.s5apply_btn.setObjectName("s5apply_btn")
        self.verticalLayout_6.addWidget(self.s5apply_btn)
        self.frame_11 = QtWidgets.QFrame(self.s5page)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_6.addWidget(self.frame_11)
        self.stackedWidget.addWidget(self.s5page)
        self.s6page = QtWidgets.QWidget()
        self.s6page.setObjectName("s6page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.s6page)
        self.verticalLayout_7.setSpacing(20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.s6page)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_7.addWidget(self.frame_12)
        self.s6n1_cekbox = QtWidgets.QCheckBox(self.s6page)
        self.s6n1_cekbox.setObjectName("s6n1_cekbox")
        self.verticalLayout_7.addWidget(self.s6n1_cekbox)
        self.s6n2_cekbox = QtWidgets.QCheckBox(self.s6page)
        self.s6n2_cekbox.setObjectName("s6n2_cekbox")
        self.verticalLayout_7.addWidget(self.s6n2_cekbox)
        self.s6n3_cekbox = QtWidgets.QCheckBox(self.s6page)
        self.s6n3_cekbox.setObjectName("s6n3_cekbox")
        self.verticalLayout_7.addWidget(self.s6n3_cekbox)
        self.s6n4_cekbox = QtWidgets.QCheckBox(self.s6page)
        self.s6n4_cekbox.setObjectName("s6n4_cekbox")
        self.verticalLayout_7.addWidget(self.s6n4_cekbox)
        self.s6apply_btn = QtWidgets.QPushButton(self.s6page)
        self.s6apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s6apply_btn.setAutoDefault(False)
        self.s6apply_btn.setDefault(False)
        self.s6apply_btn.setObjectName("s6apply_btn")
        self.verticalLayout_7.addWidget(self.s6apply_btn)
        self.frame_13 = QtWidgets.QFrame(self.s6page)
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_7.addWidget(self.frame_13)
        self.stackedWidget.addWidget(self.s6page)
        self.s7page = QtWidgets.QWidget()
        self.s7page.setObjectName("s7page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.s7page)
        self.verticalLayout_8.setSpacing(35)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_14 = QtWidgets.QFrame(self.s7page)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_8.addWidget(self.frame_14)
        self.s7n1_cekbox = QtWidgets.QCheckBox(self.s7page)
        self.s7n1_cekbox.setObjectName("s7n1_cekbox")
        self.verticalLayout_8.addWidget(self.s7n1_cekbox)
        self.s7n2_cekbox = QtWidgets.QCheckBox(self.s7page)
        self.s7n2_cekbox.setObjectName("s7n2_cekbox")
        self.verticalLayout_8.addWidget(self.s7n2_cekbox)
        self.s7apply_btn = QtWidgets.QPushButton(self.s7page)
        self.s7apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s7apply_btn.setAutoDefault(False)
        self.s7apply_btn.setDefault(False)
        self.s7apply_btn.setObjectName("s7apply_btn")
        self.verticalLayout_8.addWidget(self.s7apply_btn)
        self.frame_15 = QtWidgets.QFrame(self.s7page)
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_8.addWidget(self.frame_15)
        self.stackedWidget.addWidget(self.s7page)
        self.s8page = QtWidgets.QWidget()
        self.s8page.setObjectName("s8page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.s8page)
        self.verticalLayout_9.setSpacing(35)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_16 = QtWidgets.QFrame(self.s8page)
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_9.addWidget(self.frame_16)
        self.s8n1_cekbox = QtWidgets.QCheckBox(self.s8page)
        self.s8n1_cekbox.setObjectName("s8n1_cekbox")
        self.verticalLayout_9.addWidget(self.s8n1_cekbox)
        self.s8n2_cekbox = QtWidgets.QCheckBox(self.s8page)
        self.s8n2_cekbox.setObjectName("s8n2_cekbox")
        self.verticalLayout_9.addWidget(self.s8n2_cekbox)
        self.s8apply_btn = QtWidgets.QPushButton(self.s8page)
        self.s8apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s8apply_btn.setAutoDefault(False)
        self.s8apply_btn.setDefault(False)
        self.s8apply_btn.setObjectName("s8apply_btn")
        self.verticalLayout_9.addWidget(self.s8apply_btn)
        self.frame_17 = QtWidgets.QFrame(self.s8page)
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_9.addWidget(self.frame_17)
        self.stackedWidget.addWidget(self.s8page)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(all_compare_b2)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(all_compare_b2)

    def retranslateUi(self, all_compare_b2):
        _translate = QtCore.QCoreApplication.translate
        all_compare_b2.setWindowTitle(_translate("all_compare_b2", "Bundengan #2"))
        self.s1_btn.setText(_translate("all_compare_b2", "Senar 1"))
        self.s2_btn.setText(_translate("all_compare_b2", "Senar 2"))
        self.s3_btn.setText(_translate("all_compare_b2", "Senar 3"))
        self.s4_btn.setText(_translate("all_compare_b2", "Senar 4"))
        self.s5_btn.setText(_translate("all_compare_b2", "Senar 5"))
        self.s6_btn.setText(_translate("all_compare_b2", "Senar 6"))
        self.s7_btn.setText(_translate("all_compare_b2", "Senar 7"))
        self.s8_btn.setText(_translate("all_compare_b2", "Senar 8"))
        self.label.setText(_translate("all_compare_b2", "Pilih senar dan nada"))
        self.s1n1_cekbox.setText(_translate("all_compare_b2", "Nada Pertama (339,8 Hz)"))
        self.s1n2_cekbox.setText(_translate("all_compare_b2", "Nada Kedua (644,5 Hz)"))
        self.s1apply_btn.setText(_translate("all_compare_b2", "Lihat"))
        self.s2n1_cekbox.setText(_translate("all_compare_b2", "Nada Pertama (304,7 Hz)"))
        self.s2n2_cekbox.setText(_translate("all_compare_b2", "Nada Kedua (603,5 Hz)"))
        self.s2apply_btn.setText(_translate("all_compare_b2", "Lihat"))
        self.s3n1_cekbox.setText(_translate("all_compare_b2", "Nada Pertama (287,1 Hz)"))
        self.s3n2_cekbox.setText(_translate("all_compare_b2", "Nada Kedua (603,5Hz)"))
        self.s3n3_cekbox.setText(_translate("all_compare_b2", "Nada Ketiga (1078,1 Hz)"))
        self.s3n4_cekbox.setText(_translate("all_compare_b2", "Nada Keempat (1212,9 Hz)"))
        self.s3apply_btn.setText(_translate("all_compare_b2", "Lihat"))
        self.s4n1_cekbox.setText(_translate("all_compare_b2", "Nada Pertama (228,5 Hz)"))
        self.s4n2_cekbox.setText(_translate("all_compare_b2", "Nada Kedua (451,1 Hz)"))
        self.s4n3_cekbox.setText(_translate("all_compare_b2", "Nada Ketiga (1306,6 Hz)"))
        self.s4apply_btn.setText(_translate("all_compare_b2", "Lihat"))
        self.s5n1_cekbox.setText(_translate("all_compare_b2", "Nada Pertama (210,9 Hz)"))
        self.s5n2_cekbox.setText(_translate("all_compare_b2", "Nada Kedua (568,3 Hz)"))
        self.s5apply_btn.setText(_translate("all_compare_b2", "Lihat"))
        self.s6n1_cekbox.setText(_translate("all_compare_b2", "Nada Pertama (169,9 Hz)"))
        self.s6n2_cekbox.setText(_translate("all_compare_b2", "Nada Kedua (334,5Hz)"))
        self.s6n3_cekbox.setText(_translate("all_compare_b2", "Nada Ketiga (527,3 Hz)"))
        self.s6n4_cekbox.setText(_translate("all_compare_b2", "Nada Keempat (1072,2 Hz)"))
        self.s6apply_btn.setText(_translate("all_compare_b2", "Lihat"))
        self.s7n1_cekbox.setText(_translate("all_compare_b2", "Nada Pertama (117,2 Hz)"))
        self.s7n2_cekbox.setText(_translate("all_compare_b2", "Nada Kedua (240,2 Hz)"))
        self.s7apply_btn.setText(_translate("all_compare_b2", "Lihat"))
        self.s8n1_cekbox.setText(_translate("all_compare_b2", "Nada Pertama (99,6 Hz)"))
        self.s8n2_cekbox.setText(_translate("all_compare_b2", "Nada Kedua (205 Hz)"))
        self.s8apply_btn.setText(_translate("all_compare_b2", "Lihat"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    all_compare_b2 = QtWidgets.QDialog()
    ui = Ui_all_compare_b2()
    ui.setupUi(all_compare_b2)
    all_compare_b2.show()
    sys.exit(app.exec_())

