# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'all_compare_b1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_all_compare_b1(object):
    def setupUi(self, all_compare_b1):
        all_compare_b1.setObjectName("all_compare_b1")
        all_compare_b1.resize(500, 400)
        all_compare_b1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(all_compare_b1)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(all_compare_b1)
        self.frame.setMinimumSize(QtCore.QSize(0, 280))
        self.frame.setStyleSheet("QPushButton{\n"
"    color: rgb(77, 77, 77);\n"
"    border: 0.5px solid rgb(191, 191, 191);\n"
"    border-radius: 4px;\n"
"    padding-top:7px;\n"
"    padding-bottom:7px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #303f9f;\n"
"    border: 0px;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:default{\n"
"    background-color: #303f9f;\n"
"    border: 0px;\n"
"    color: #ffffff;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.s1_btn = QtWidgets.QPushButton(self.frame_2)
        self.s1_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s1_btn.setAutoDefault(False)
        self.s1_btn.setObjectName("s1_btn")
        self.verticalLayout_3.addWidget(self.s1_btn)
        self.s2_btn = QtWidgets.QPushButton(self.frame_2)
        self.s2_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s2_btn.setAutoDefault(False)
        self.s2_btn.setObjectName("s2_btn")
        self.verticalLayout_3.addWidget(self.s2_btn)
        self.s3_btn = QtWidgets.QPushButton(self.frame_2)
        self.s3_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s3_btn.setAutoDefault(False)
        self.s3_btn.setObjectName("s3_btn")
        self.verticalLayout_3.addWidget(self.s3_btn)
        self.s4_btn = QtWidgets.QPushButton(self.frame_2)
        self.s4_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s4_btn.setAutoDefault(False)
        self.s4_btn.setObjectName("s4_btn")
        self.verticalLayout_3.addWidget(self.s4_btn)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMaximumSize(QtCore.QSize(229, 278))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome_page = QtWidgets.QWidget()
        self.welcome_page.setObjectName("welcome_page")
        self.label = QtWidgets.QLabel(self.welcome_page)
        self.label.setGeometry(QtCore.QRect(30, 110, 171, 50))
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setStyleSheet("color: rgb(77, 77, 77);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.welcome_page)
        self.s1page = QtWidgets.QWidget()
        self.s1page.setObjectName("s1page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.s1page)
        self.verticalLayout_4.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.s1n1_cekbox = QtWidgets.QCheckBox(self.s1page)
        self.s1n1_cekbox.setObjectName("s1n1_cekbox")
        self.verticalLayout_4.addWidget(self.s1n1_cekbox)
        self.s1n2_cekbox = QtWidgets.QCheckBox(self.s1page)
        self.s1n2_cekbox.setObjectName("s1n2_cekbox")
        self.verticalLayout_4.addWidget(self.s1n2_cekbox)
        self.s1n3_cekbox = QtWidgets.QCheckBox(self.s1page)
        self.s1n3_cekbox.setObjectName("s1n3_cekbox")
        self.verticalLayout_4.addWidget(self.s1n3_cekbox)
        self.s1n4_cekbox = QtWidgets.QCheckBox(self.s1page)
        self.s1n4_cekbox.setObjectName("s1n4_cekbox")
        self.verticalLayout_4.addWidget(self.s1n4_cekbox)
        self.frame_4 = QtWidgets.QFrame(self.s1page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.s1apply_btn = QtWidgets.QPushButton(self.frame_4)
        self.s1apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s1apply_btn.setAutoDefault(False)
        self.s1apply_btn.setDefault(False)
        self.s1apply_btn.setObjectName("s1apply_btn")
        self.horizontalLayout_2.addWidget(self.s1apply_btn)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.s1page)
        self.s2page = QtWidgets.QWidget()
        self.s2page.setObjectName("s2page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.s2page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.s2n1_cekbox = QtWidgets.QCheckBox(self.s2page)
        self.s2n1_cekbox.setObjectName("s2n1_cekbox")
        self.verticalLayout_5.addWidget(self.s2n1_cekbox)
        self.s2n2_cekbox = QtWidgets.QCheckBox(self.s2page)
        self.s2n2_cekbox.setObjectName("s2n2_cekbox")
        self.verticalLayout_5.addWidget(self.s2n2_cekbox)
        self.frame_5 = QtWidgets.QFrame(self.s2page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.s2apply_btn = QtWidgets.QPushButton(self.frame_5)
        self.s2apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s2apply_btn.setAutoDefault(False)
        self.s2apply_btn.setDefault(False)
        self.s2apply_btn.setObjectName("s2apply_btn")
        self.horizontalLayout_3.addWidget(self.s2apply_btn)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.s2page)
        self.s3page = QtWidgets.QWidget()
        self.s3page.setObjectName("s3page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.s3page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.s3n1_cekbox = QtWidgets.QCheckBox(self.s3page)
        self.s3n1_cekbox.setObjectName("s3n1_cekbox")
        self.verticalLayout_6.addWidget(self.s3n1_cekbox)
        self.s3n2_cekbox = QtWidgets.QCheckBox(self.s3page)
        self.s3n2_cekbox.setObjectName("s3n2_cekbox")
        self.verticalLayout_6.addWidget(self.s3n2_cekbox)
        self.s3apply_btn = QtWidgets.QPushButton(self.s3page)
        self.s3apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s3apply_btn.setAutoDefault(False)
        self.s3apply_btn.setDefault(False)
        self.s3apply_btn.setObjectName("s3apply_btn")
        self.verticalLayout_6.addWidget(self.s3apply_btn)
        self.stackedWidget.addWidget(self.s3page)
        self.s4page = QtWidgets.QWidget()
        self.s4page.setObjectName("s4page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.s4page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.s4n1_cekbox = QtWidgets.QCheckBox(self.s4page)
        self.s4n1_cekbox.setObjectName("s4n1_cekbox")
        self.verticalLayout_7.addWidget(self.s4n1_cekbox)
        self.s4n2_cekbox = QtWidgets.QCheckBox(self.s4page)
        self.s4n2_cekbox.setObjectName("s4n2_cekbox")
        self.verticalLayout_7.addWidget(self.s4n2_cekbox)
        self.s4apply_btn = QtWidgets.QPushButton(self.s4page)
        self.s4apply_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s4apply_btn.setAutoDefault(False)
        self.s4apply_btn.setDefault(False)
        self.s4apply_btn.setObjectName("s4apply_btn")
        self.verticalLayout_7.addWidget(self.s4apply_btn)
        self.stackedWidget.addWidget(self.s4page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(all_compare_b1)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(all_compare_b1)

    def retranslateUi(self, all_compare_b1):
        _translate = QtCore.QCoreApplication.translate
        all_compare_b1.setWindowTitle(_translate("all_compare_b1", "Bundengan #1"))
        self.s1_btn.setText(_translate("all_compare_b1", "Senar 1"))
        self.s2_btn.setText(_translate("all_compare_b1", "Senar 2"))
        self.s3_btn.setText(_translate("all_compare_b1", "Senar 3"))
        self.s4_btn.setText(_translate("all_compare_b1", "Senar 4"))
        self.label.setText(_translate("all_compare_b1", "Pilih senar dan nada"))
        self.s1n1_cekbox.setText(_translate("all_compare_b1", "Nada Pertama (234,4 Hz)"))
        self.s1n2_cekbox.setText(_translate("all_compare_b1", "Nada Kedua (468,7 Hz)"))
        self.s1n3_cekbox.setText(_translate("all_compare_b1", "Nada Ketiga (609 Hz)"))
        self.s1n4_cekbox.setText(_translate("all_compare_b1", "Nada Keempat (1207 Hz)"))
        self.s1apply_btn.setText(_translate("all_compare_b1", "Lihat"))
        self.s2n1_cekbox.setText(_translate("all_compare_b1", "Nada Pertama (181,6 Hz)"))
        self.s2n2_cekbox.setText(_translate("all_compare_b1", "Nada Kedua (375 Hz)"))
        self.s2apply_btn.setText(_translate("all_compare_b1", "Lihat"))
        self.s3n1_cekbox.setText(_translate("all_compare_b1", "Nada Pertama (99,6 Hz)"))
        self.s3n2_cekbox.setText(_translate("all_compare_b1", "Nada Kedua (199,2 Hz)"))
        self.s3apply_btn.setText(_translate("all_compare_b1", "Lihat"))
        self.s4n1_cekbox.setText(_translate("all_compare_b1", "Nada Pertama (70,3 Hz)"))
        self.s4n2_cekbox.setText(_translate("all_compare_b1", "Nada Kedua (146,5 Hz)"))
        self.s4apply_btn.setText(_translate("all_compare_b1", "Lihat"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    all_compare_b1 = QtWidgets.QDialog()
    ui = Ui_all_compare_b1()
    ui.setupUi(all_compare_b1)
    all_compare_b1.show()
    sys.exit(app.exec_())

